<div class="container" style="margin-top: 2em;">
    <div class="panel panel-default app-content">
    <div class="panel-heading">
        <h3>Create new</h3>
    </div>
    <div class="panel-body">
        <?php echo $this->form; ?>
    </div>
    </div>
</div>

<div class="container">
    <div class="row">
    <?php echo Functions_View::listVideos($this->videos); ?>
    </div>
    <div class="row">
    <div class='pages col-md-12'>
        <?php
            echo $this->partial('_partials/pagination.phtml',
            array(
            'paginator'=>$this->paginator->getPages(),
            'baseUrl'=>'/' . '?q=' . $this->query . '&p='
            ));
        ?>
    </div>
    </div>
</div>