<div id="analytics-wrapper">
	<div id="analytics-stage"></div>
</div>

<script src="/js/libraries/highcharts/highcharts.js"></script>
<script src="/js/libraries/highcharts/highcharts-exporting.js"></script>
<script src="/js/core/services/LLAnalyticService.js"></script>
<script src="/js/core/userinterface/components/analytics/LLAnalyticsChart.js"></script>
<script src="/js/core/userinterface/components/analytics/LLAnalyticsCalendar.js"></script>
<script src="/js/core/userinterface/components/analytics/LLAnalyticsClock.js"></script>
<script src="/js/core/userinterface/components/analytics/LLAnalyticsChartLayout.js"></script>