<h1>Reset Password</h1>
<p>Please enter your email to proceed to reset your password.</p>
<?php if($this->errorMessage): ?>
    <div class="errors"><?php echo $this->errorMessage; ?></div>
<?php endif; ?>
<?php
    echo $this->form;
?>
<script>
    var postedStudent = '<?php echo $this->studentData; ?>';
    if(postedStudent != "") {
        $("#container-header, #container-footer, #navbar, #sidebar").hide();
        $("html").css({overflow:"hidden"});
        if(postedStudent == "passwordResetSuccess") {
            $("#container-main h1, #container-main p, #container-main form, #client-forgot-password-submit").hide();
            var sendNoticeButton = '<br><br><input type="button" value="Click to login with your new password" onclick="sendReLoginMessage()"/>';
            $("#container-main").append(sendNoticeButton);
        }
        if ( postedStudent == "resetPasswordInvalidUser") {
            $("#container-main h1, #container-main p, #container-main form, #client-forgot-password-submit").hide();
            var messsage = '<br><br><h3>User did not match. Please close this panel and try again.</h3>';
            $("#container-main").append(messsage);
        }
    }
    jQuery(window).load(function() {
        $.extend({
            getUrlVars: function() {
                var vars = [], hash;
                var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
                for(var i = 0; i < hashes.length; i++) {
                    hash = hashes[i].split('=');
                    vars.push(hash[0]);
                    vars[hash[0]] = hash[1];
                }
                return vars;
            },
            getUrlVar: function(name){
                return $.getUrlVars()[name];
            }
        });
        var getStudent = $.getUrlVar('studentData');
        if(getStudent) {
            // don't show header & footer in login screen
            $("#container-header, #container-footer, #navbar, #sidebar").hide();
            $("html").css({overflow:"hidden"});
            $("#studentData").val(getStudent);
        }
    });
    function sendReLoginMessage() {
        var parameters = new Object();
        parameters.message  = "reopenLogin";
        parent.postMessage(JSON.stringify(parameters),'*');
    }
</script>