<h1>Reset Your Password</h1>
<p>Please enter your new password to proceed to reset your password.</p>
<?php if($this->errorMessage): ?>
    <div class="errors"><?php echo $this->errorMessage; ?></div>
<?php endif; ?>
<?php
    echo $this->form;
?>
<script>
    var postedStudent = '<?php echo $this->studentData; ?>';
    if(postedStudent != "") {
        $("#container-header, #container-footer, #navbar, #sidebar").hide();
        $("html").css({overflow:"hidden"});

    }

    jQuery(window).load(function() {
        // jQuery ready
        $.extend({
            getUrlVars: function() {
                var vars = [], hash;
                var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
                for(var i = 0; i < hashes.length; i++) {
                    hash = hashes[i].split('=');
                    vars.push(hash[0]);
                    vars[hash[0]] = hash[1];
                }
                return vars;
            },
            getUrlVar: function(name){
                return $.getUrlVars()[name];
            }
        });
        var getStudent = $.getUrlVar('studentData');
        if(getStudent) {
            // don't show header & footer in login screen
            $("#container-header, #container-footer, #navbar, #sidebar").hide();
            $("html").css({overflow:"hidden"});
            $("#studentData").val(getStudent);
        }
    });

</script>