<div class="panel panel-default app-content">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-primary" id="app-save-submit">Save</button>
            <button type="button" class="btn btn-danger" id="app-delete">Delete</button>
        </div>
        <div class="pull-right">&nbsp;</div>
        <div class="btn-group pull-right">
        </div>
        <h3 id="appName" rel="<?php echo $this->app->id; ?>"><?php echo $this->app->name; ?></h3>
    </div>
    <div class="panel-body">
        <p>Manage App: <?php echo $this->app->name; ?></p>
    </div>
    <div class="row container">
        <div class="col-md-6">
            <h3>Details</h3>
            <?php echo $this->form; ?>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5>Packages</h5>
                        </div>
                        <?php echo Functions_View::listPackageContents(Repo_Package::getInstance()->getClientPackages($this->client->id), $this->appPackages, 'Repo_Package', 'appPackages'); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5>Users</h5>
                        </div>
                        <?php echo Functions_View::listTeamContents(Repo_User::getInstance()->getClientUsers($this->client->id), $this->appUsers, 'Repo_User', 'appUsers'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo
    Functions_View::deleteModal(
        'Confirm Delete App',
        'Please make sure you want to delete this app'
    );
?>