<div class="panel panel-default app-content">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <h3 id="clientName" rel="<?php echo $this->client->id; ?>"><?php echo $this->client->name; ?></h3>
    </div>
    <div class="panel-body">
        <p>Manage client: <?php echo $this->client->name; ?></p>
    </div>
    <div class="row container">
        <div class="col-md-12">
            <ul>
                <li><a href="/admin/client/upload-pages/id/<?php echo $this->client->id; ?>">Bulk upload & generate pages</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <div type="button" class="btn btn-primary pull-right" id="client-edit-save">Save</div>
        <h3 id="clientName" rel="<?php echo $this->client->id; ?>">Edit</h3>
    </div>
    <div class="panel-body">
        <p>Edit client: <?php echo $this->client->name; ?></p>
    </div>
    <div class="row container">
        <div class="col-md-12">
            <?php echo $this->form; ?>
        </div>
    </div>

    <br><br>

</div>