<div class="panel panel-default app-content">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <a href="/admin/client/new-library" class="btn btn-primary" id="create-new-library">New Library</a>
        </div>
        <div class="pull-right">&nbsp;</div>
        <div class="btn-group pull-right">
            <div class="btn-group">
                <?php echo Functions_View::libraryStatusFilter(
                        $this->status ? Repo_Library::$statusLabels[$this->status] : false,
                        'library-status-filter',
                        $this->status
                    );
                ?>
            </div>
        </div>
        <h3>Libraries</h3>
    </div>
    <div class="panel-body">
        <p>Manage libraries, some guidelines or description</p>
    </div>
    <?php echo Functions_View::listLibraries($this->libraries); ?>
</div>