<script src="../../../../js/admin/client/surveymenufunctions.js"></script>
<script src="../../../../js/admin/client/file.js"></script>
<div class="panel panel-default app-content">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-primary" id="survey-save-submit">Save</button>
        </div>
        <h3 id="pageName">Create a new survey</h3>
    </div>
    <div class="panel-body">
        <p>Create a new survey for a client.</p>
    </div>
    <div class="row container">
        <div class="col-md-6">
            <h3>Details</h3>
            <?php echo $this->form; ?>
        </div>
    </div>
</div>