<div ng-app="pageTemplateDetailApp"><div ng-controller="PageTemplateDetailCtrl">
<div class="panel panel-default app-content">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-primary" id="save-submit">Save</button>
            <!--button type="button" class="btn btn-success" id="publish">Publish</button-->
            <button type="button" class="btn btn-danger" id="delete">Delete</button>
        </div>
        <h3 id="pageTemplateName" rel="<?php echo $this->template->id; ?>" client="<?php echo $this->template->client_id; ?>">
            <?php echo $this->template->name; ?>
        </h3>
    </div>
    <div class="panel-body">
        <p>Manage Page Template: <?php echo $this->template->name; ?></p>
    </div>
    <div class="row container">
        <div class="col-md-12">
            <h3>Details</h3>
            <?php echo $this->form; ?>
        </div>
    </div>
</div>

<?php echo Functions_View::formModal(new Form_Admin_Client_PageTemplate_Publish()); ?>
<?php echo
    Functions_View::deleteModal(
        'Confirm Delete',
        'Please make sure you want to delete this template'
    );
?>
<script type="text/javascript">
    var modelTags = <?php echo Zend_Json::encode($this->template->getTags()); ?>;
</script>
</div></div>