<div class="panel panel-default app-content">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <a href="/admin/client/new-page-template" class="btn btn-primary" id="create-new">New Page Template</a>
        </div>
        <h3>Page Templates</h3>
    </div>
    <div class="panel-body">
        <p>Manage Page templates, some guidelines or description</p>
    </div>
    <?php echo Functions_View::listPageTemplates($this->templates); ?>
</div>