<style type="text/css">
    .response-text-panel {
        display:none;
        position:fixed;
        width:92%;
        height:auto;
        padding-bottom:15px;
        top:20%;
    }
    .response-text-panel .inner {
        overflow-y:auto;
    }
    .response-text-panel textarea {
        width:100%;
    }
    .btn-delete-option {
        cursor:pointer;
    }
    .btn-open-optionoptions {
        cursor:pointer;
    }
    .btn-sort-view-mode {
        position: relative;
        display: inline-block;
        float: left;
        top: 20px;
    }
    .show-no-events {
        pointer-events: none;
        opacity:0.4;
    }
    .close.delete-question-item-button {
        position: absolute;
        top: 5px;
        right: 5px;
    }
    .question-list-control-div {
        text-align:right; width:100%; margin-top:-15px; height:70px;
    }
</style>
<script src="../../../../js/admin/client/surveymenufunctions.js"></script>
<script src="../../../../js/admin/client/file.js"></script>
<script src="../../../../js/admin/client/Paginator.js"></script>
<script>
    var feedbackQuestionTypeLabels = JSON.parse('<?= $this->feedbackQuestionTypeLabels; ?>');
    var csvError = '<?= $this->csvError; ?>';
</script>
<div class="panel panel-default app-content">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <div class="btn-group pull-right">

            <button type="button" class="btn btn-primary" id="survey-save-submit">Save</button>
            <button type="button" class="btn btn-danger" id="survey-delete">Delete</button>
        </div>
        <div class="pull-right">&nbsp;</div>
        <div class="btn-group pull-right">
            <div class="btn-group">
                <?php
                echo Functions_View::surveyStatusFilter(
                        $this->status ? Repo_Survey::$statusLabels[$this->status] : false, 'survey-status-filter', $this->status
                );
                ?>
            </div>
        </div>
        <h3 id="surveyName" rel="<?php echo $this->survey->id; ?>"><?php echo $this->survey->name; ?></h3>
    </div>
    <div class="panel-body">
        <p>Manage survey: <?php echo $this->survey->name; ?></p>
    </div>
    <div class="row container">
        <div class="col-md-6">
            <h3>Details</h3>
            <?php echo $this->form; ?>

            <?php if ($this->childClients && count($this->childClients)): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Client Access</h3>
                </div>
                <?php echo Functions_View_ResourceAccess::listClientsRecursively($this->childClients, $this->accessClients); ?>
            </div>
            <?php endif; ?>

        </div>
        <div class="col-md-6">
            <h3>Add/Edit Questions</h3>
            <?php
            $question_view_limit = 5;
            //get repository of question data
            $survey_questions = $this->surveyQuestions->toArray();
            $n_surveyQuestions = count($survey_questions);

            $no_questions_message = ($n_surveyQuestions <= 0) ? 'Survey has no questions' : '';
            echo "<label>" . $no_questions_message . "</label><br/>";

            if ($n_surveyQuestions > 0) {
                //toggle between sort and edit
                echo '<div class="question-list-control-div">';
                echo '<button type="button" class="btn btn-primary btn-sort-view-mode" id="btn-sort-mode" onclick="questionListView(\'sort\')" >SORT QUESTIONS</button>';
                echo '<button type="button" class="btn btn-primary btn-sort-view-mode" id="btn-edit-mode" onclick="questionListView(\'edit\')" >EDIT QUESTIONS</button>';


                echo '</div>';

                //paginator

                if ($n_surveyQuestions > $question_view_limit) {
                    $chunk = ceil($n_surveyQuestions / $question_view_limit);
                    ?>
                    <script language="javascript">
                        var params = {numberPages:<?php echo $chunk; ?>, onclickCallback: 'paginatorHandler', range:<?php echo $question_view_limit; ?>, paginatorName: "PAGINATOR"};
                        var PAGINATOR = new Paginator(params);
                        PAGINATOR.getPaginator();
                        num_surveyQuestions = <?php echo $n_surveyQuestions; ?>
                    </script>
                    <?php
                }

                echo '<ul class="list-group title-pages-list connectedSortable" id="survey-questions">';
                echo Functions_View::listQuestionEditGroup($this->surveyQuestions->toArray(), 'li', 'page-list-item list-group-item');
                echo '</ul>';
            }
            ?>

            <button type="button" class="btn btn-primary" id="btn-add-question">ADD QUESTION</button>
        </div>
        <div class="col-md-6">
            <h3>Add / Edit Tags</h3>
            <button type="button" class="btn btn-primary" id="btn-add-tag">Add Tag</button>
            <button type="button" class="btn btn-danger" id="btn-delete-tag">Delete Tag</button>
            <?php
            echo Functions_View::addTagToSurveyModal();

            $data = Repo_SurveyTag::getInstance()->
                    getTagBySurveyId(Zend_Controller_Front::getInstance()
                            ->getRequest()
                            ->getParam('id'));
            echo '<table id="tag-listings" class="table table-striped table-bordered">';
            echo '<thead><th>Tag</th><th>Select</th></thead>';
            foreach ($data as $dat) {
                echo '<tr><td>' . $dat['name'] . '</td><td><div class="checkbox" tag_id="'.$dat['id'].'"></div></td></tr>';
            }
            echo '</table>';
            ?>

        </div>
    </div>


    <?php
    echo Functions_View::deleteModal(
            'Confirm Delete Survey', 'Please make sure you want to delete this survey'
    );

    $add_question_form = new Form_Admin_Client_Question_Add(null, array("surveyid" => $this->survey->id, "titleid" => $this->survey->title_id));

    $add_question_form->setDecorators(array(
        array('ViewScript', array('viewScript' => 'client/question-add-viewscript.phtml'))
    ));

    echo Functions_View::formModal($add_question_form);
    echo Functions_View::addTagToQuestionModal();
    echo Functions_View::addOptionType();

    ?>

</div>
<script>
    $(document).ready( function() {
        if(csvError != '') {
            $("#files").next('span').html(csvError);
        } else {
            var getError = $("#files").next('span').html();
            if( getError ) {
                if( getError.indexOf( 'is not readable or does not exist') != -1 ) {
                    $("#files").next('span').removeClass("errors");
                    $("#files").next('span').html('');
                }
            }
        }
    })
</script>