<div class="panel panel-default app-content">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-success" id="title-clone">Clone</button>
        </div>
        <div class="pull-right">&nbsp;</div>
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-primary" id="title-save-submit">Save</button>
            <button type="button" class="btn btn-danger" id="title-delete">Delete</button>
        </div>
        <div class="pull-right">&nbsp;</div>
        <div class="btn-group pull-right">
            <div class="btn-group">
                <?php echo Functions_View::titleStatusFilter(
                        $this->status ? Repo_Title::$statusLabels[$this->status] : false,
                        'title-status-filter',
                        $this->status
                    );
                ?>
            </div>
        </div>
        <h3 id="titleName" rel="<?php echo $this->title->id; ?>"><?php echo $this->title->name; ?></h3>
    </div>
    <div class="panel-body">
        <p>Manage title: <?php echo $this->title->name; ?></p>
    </div>
    <div class="row container">
        <div class="col-md-6">
            <h3>Details</h3>
            <?php echo $this->form; ?>
        </div>
    </div>
    <div class="row container">
        <div class="col-md-12">
            <h3>Pages</h3>
            <div class="row">
                <div id="pages-out" class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5>Pages</h5>
                        </div>
                        <ul class="list-group client-pages-list connectedSortable" id="client-pages">
                            <?php echo Functions_View::listPageGroup($this->clientPages, 'li', 'page-list-item list-group-item'); ?>
                        </ul>
                    </div>
                </div>
                <div id="pages-in" class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5>Title Pages</h5>
                        </div>
                        <ul class="list-group title-pages-list connectedSortable" id="title-pages">
                            <?php echo Functions_View::listPageGroup($this->titlePages->toArray(), 'li', 'page-list-item list-group-item'); ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo
    Functions_View::deleteModal(
        'Confirm Delete Title',
        'Please make sure you want to delete this title'
    );
?>