<div class="panel panel-default app-content">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-primary" id="upload-submit">Upload & Generate Pages</button>
        </div>
        <h3 id="clientName" rel="<?php echo $this->client->id; ?>">Bulk Upload & Generate Pages</h3>
    </div>
    <div class="panel-body">
        <p>Bulk upload & generate pages for client: <b><?php echo $this->client->name; ?></b></p>
    </div>
    <div class="row container">
        <div class="col-md-6">
            <h3>Details</h3>
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
<?php echo Functions_View::formModal(new Form_Admin_Client_Title()); ?>