<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to Free HD Video Footage Download<?php echo $this->query ? ': ' . $this->query : ''; ?></h1>
    <p>You can preview all the free-to-use HD video footage here. Download them by using a third party tool from youtube. All the videos have the creative commons attribution license.</p>
  </div>
</div>

<div class="container">
    <div class="row">
    <?php echo Functions_View::listVideos($this->videos); ?>
    </div>
    <div class="row">
    <div class='pages col-md-12'>
        <?php
            echo $this->partial('_partials/pagination.phtml',
            array(
            'paginator'=>$this->paginator->getPages(),
            'baseUrl'=>'/' . '?q=' . $this->query . '&p='
            ));
        ?>
    </div>
    </div>
</div>