<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headTitle($this->headTitle ? $this->headTitle : 'Lifelearn Stratus') . "\n"; ?>
        <?php echo $this->headMeta() . "\n"; ?>
        <!-- Bootstrap -->
        <link href='https://fonts.googleapis.com/css?family=Roboto:700,500,400,300' rel='stylesheet' type='text/css'>

        <!--<link href="/css/all.css" rel="stylesheet" media="screen">-->
        <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">

        <link href="/css/app.css" rel="stylesheet" media="screen">


        <link href="/css/analytics.css" rel="stylesheet" media="screen">
        <link href="/css/ionicicons.css" rel="stylesheet" media="screen">
        <!--<link href="/css/configmenu.css" rel="stylesheet" media="screen">-->
        <link href="/js/libraries/nanoscroller/css/nanoscroller.css" rel="stylesheet" media="screen">
        <link rel="icon" type="image/png" href="/client/favicon.png">
        <?php echo $this->headLink() . "\n"; ; ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>
        <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="/js/libraries/bootstrap/bootstrap.min.js"></script>
        <script src="/js/libraries/tablesorter/tablesorter.min.js"></script>
        <script src="/js/client/action.js"></script>
        <script src="/js/client/menu.js"></script>
        <script src="/js/libraries/nanoscroller/jquery.nanoscroller.min.js"></script>
        <script>
            $(document).ready(function(){
               $(".nano").nanoScroller();
            });
            </script>
        <?php echo $this->headScript() . "\n"; ; ?>
    </head>
    <body>
        <?php echo $this->render('client-header.phtml'); ?>
        <div id="container-body" class="container container-body-open app-transition-ease">
        	<div id="container-main">
                <?php
                    if ($this->flashMessages) {
                        foreach ($this->flashMessages as $_m) {
                            echo '<button class="btn btn-success">' . $_m . '</button>';
                        }
                    }
                ?>
           		<?php echo $this->layout()->content; ?>
           	</div>
        </div>
        <?php echo $this->render('client-footer.phtml'); ?>
    </body>
</html>
