<script>
    <?php $identity = Zend_Auth::getInstance()->getIdentity(); ?>
    <?php if($identity): ?>
    var userEmail = "<?php echo $identity->email; ?>";
    var userClientId = "<?php echo $identity->client_id; ?>";
    <?php endif; ?>
</script>

<div id="navbar">

    <div id="logo">
        <div id="logo-title">STRATUS</div>
        <div id="logo-subtitle">Lifelearn</div>
    </div>



    <?php if ($this->clientContext->getId() > 0): ?>

    <?php endif; ?>

    <div id="menu-logout" class="menu link">
        <span class="menu-logout-icon ion-power"></span>Logout
    </div>

    <?php if (Auth_Wrapper_User::userHasPermission("/client/index/change-password")) { ?>
        <div id="menu-settings" class="menu">
            <?php echo Functions_View::configMenu(); ?>
        </div>
    <?php } ?>
    

    <div id="menu-clients" class="menu">
        <?php echo Functions_View::menuClients($this->clientName); ?>
    </div>



    
    <div id="menu-mobile" class="menu">
        <?php if (Auth_Wrapper_User::userHasPermission("/client/index/change-password")) { ?>
            <?php echo Functions_View::configMenuMobile(); ?>
        <?php } ?>
    </div>

    

    <!--<div id="menu-filter" class="menu">Filters</div>-->
    


    
</div>



<div id="sidebar" class="sidebar-open app-transition-ease">

    <div id="sidebar-toggle-stage">
        <div id="sidebar-toggle" class="sidebar-toggle-open">
            <div class="sidebar-toggle-left ion-chevron-left"></div>
            <div class="sidebar-toggle-right ion-chevron-right"></div>
        </div>
    </div>
    
    <div id="sidebar-content-stage" class="nano">

        <div id="sidebar-content" class="nano-content">
            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/')): ?>
                <div id="sidebar-client" class="sidebar list" href="/admin/client/"><span class="sidebar-icon ion-briefcase"></span><span class="sidebar-title">Clients</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/review-portal')): ?>
                <div id="sidebar-portal" class="sidebar list" href="/admin/review-portal"><span class="sidebar-icon ion-chatbubbles"></span><span class="sidebar-title">Review Portals</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/user')): ?>
                <div id="sidebar-user" class="sidebar list" href="/admin/client/user"><span class="sidebar-icon ion-person"></span><span class="sidebar-title">Users</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/team')): ?>
                <div id="sidebar-team" class="sidebar list" href="/admin/client/team"><span class="sidebar-icon ion-person-stalker"></span><span class="sidebar-title">Teams</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/page')): ?>
                <div id="sidebar-page" class="sidebar list" href="/admin/client/page"><span class="sidebar-icon ion-image"></span><span class="sidebar-title">Pages</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/title')): ?>
                <div id="sidebar-title" class="sidebar list" href="/admin/client/title"><span class="sidebar-icon ion-images"></span><span class="sidebar-title">Titles</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/package')): ?>
                <div id="sidebar-package" class="sidebar list" href="/admin/client/package"><span class="sidebar-icon ion-folder"></span><span class="sidebar-title">Packages</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/app')): ?>
                <div id="sidebar-app" class="sidebar list" href="/admin/client/app"><span class="sidebar-icon ion-filing"></span><span class="sidebar-title">Apps</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/form')): ?>
                <div id="sidebar-form" class="sidebar list" href="/admin/client/form"><span class="sidebar-icon ion-clipboard"></span><span class="sidebar-title">Forms</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/survey')): ?>
                <div id="sidebar-survey" class="sidebar list" href="/admin/client/survey"><span class="sidebar-icon ion-clipboard"></span><span class="sidebar-title">Surveys</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/result')): ?>
                <div id="sidebar-result" class="sidebar list" href="/admin/client/result"><span class="sidebar-icon ion-connection-bars"></span><span class="sidebar-title">Results</span></div>
                
            <?php endif; ?>
            <?php if (Auth_Wrapper_User::userHasPermission('/admin/survey-quiz/display-quiz')): ?>
                <div id="sidebar-survey-quiz" class="sidebar list" href="/admin/survey-quiz/display-quiz"><span class="sidebar-icon ion-connection-bars"></span><span class="sidebar-title">Survey & Quiz Results</span></div>
                
            <?php endif; ?>
            <?php if (Auth_Wrapper_User::userHasPermission('/admin/document')): ?>
                <div id="sidebar-document" class="sidebar list" href="/admin/document"><span class="sidebar-icon ion-document-text"></span><span class="sidebar-title">Documents</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/pdf-template')): ?>
                <div id="sidebar-pdf-template" class="sidebar list" href="/admin/client/pdf-template"><span class="sidebar-icon ion-image"></span><span class="sidebar-title">Pdf Template</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/page-template')): ?>
                <div id="sidebar-page-template" class="sidebar list" href="/admin/client/page-template"><span class="sidebar-icon ion-image"></span><span class="sidebar-title">Page Template</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/contact')): ?>
                <div id="sidebar-contact" class="sidebar list" href="/admin/client/contact"><span class="sidebar-icon ion-person"></span><span class="sidebar-title">Contacts</span></div>
                
            <?php endif; ?>

            <div id="sidebar-analytics" class="sidebar list" href="/admin/"><span class="sidebar-icon ion-pie-graph"></span><span class="sidebar-title">Analytics</span></div>
            
            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/result')): ?>
                <div id="sidebar-tags" class="sidebar list" href="/admin/client/tag"><span class="sidebar-icon ion-pricetag"></span><span class="sidebar-title">Tags</span></div>
                
            <?php endif; ?>
            <?php if (Auth_Wrapper_User::userHasPermission('/admin/client/result')): ?>
                <div id="sidebar-survey-chart" class="sidebar list" href="/admin/client/survey-chart"><span class="sidebar-icon ion-stats-bars"></span><span class="sidebar-title">Survey Chart</span></div>
                
            <?php endif; ?>

            <?php if (Auth_Wrapper_User::userHasPermission('/admin/media-asset')): ?>
                <div id="sidebar-media-asset" class="sidebar list" href="/admin/media-asset"><span class="sidebar-icon ion-eye"></span><span class="sidebar-title">Media Library</span></div>

            <?php endif; ?>

            <!--
            <?php if (Auth_Wrapper_User::isUserSuperAdmin()): ?>
                <div id="sidebar-roles-and-permissions" class="sidebar list" href="/admin/config/role"><span class="sidebar-icon ion-levels"></span><span class="sidebar-title">Roles & Permissions</span></div>
                
            <?php endif; ?>
            <?php if (Auth_Wrapper_User::userHasPermission("/client/index/change-password")): ?>
                <div id="sidebar-reset-password" class="sidebar list" href="/client/index/change-password"><span class="sidebar-icon ion-locked"></span><span class="sidebar-title">Reset Password</span></div>
                
            <?php endif; ?>
            <div id="sidebar-logout" class="sidebar list" href="/logout"><span class="sidebar-icon ion-power"></span><span class="sidebar-title">Logout</span></div>
            <div id="sidebar-control">
                <div id="sidebar-control-icon" class="sidebar-control-min"></div>
            </div>
            -->
        </div>

    </div>
</div>

<div id="overlay"></div>

<div id="loader">
    <div id="loader-info"></div>
</div>